package service

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/mrAboalfazl/dnstt-manager/config"
	"github.com/mrAboalfazl/dnstt-manager/models"
)

type ClientConfig struct {
	Domain      string `json:"domain"`
	PubKey      string `json:"pubkey"`
	SSHUser     string `json:"ssh_user"`
	SSHPass     string `json:"ssh_pass"`
	SSHPort     int    `json:"ssh_port"`
	DNSResolver string `json:"dns_resolver"`
	MTU         int    `json:"mtu"`
	ServerIP    string `json:"server_ip"`
}

func GenerateUserConfig(user *models.User, plainPassword string) (*ClientConfig, error) {
	cfg := config.Get()

	pubkey := ""
	if data, err := os.ReadFile(cfg.PubKeyFile); err == nil {
		pubkey = strings.TrimSpace(string(data))
	}

	return &ClientConfig{
		Domain:      cfg.DNSTTDomain,
		PubKey:      pubkey,
		SSHUser:     user.Username,
		SSHPass:     plainPassword,
		SSHPort:     cfg.SSHPort,
		DNSResolver: cfg.DNSResolver,
		MTU:         cfg.MTU,
		ServerIP:    cfg.ServerIP,
	}, nil
}

func GenerateConfigForExistingUser(user *models.User) (*ClientConfig, error) {
	cfg := config.Get()

	pubkey := ""
	if data, err := os.ReadFile(cfg.PubKeyFile); err == nil {
		pubkey = strings.TrimSpace(string(data))
	}

	return &ClientConfig{
		Domain:      cfg.DNSTTDomain,
		PubKey:      pubkey,
		SSHUser:     user.Username,
		SSHPass:     "********",
		SSHPort:     cfg.SSHPort,
		DNSResolver: cfg.DNSResolver,
		MTU:         cfg.MTU,
		ServerIP:    cfg.ServerIP,
	}, nil
}

func GenerateLink(user *models.User) (string, error) {
	cfg := config.Get()

	pubkey := ""
	if data, err := os.ReadFile(cfg.PubKeyFile); err == nil {
		pubkey = strings.TrimSpace(string(data))
	}

	linkData := map[string]interface{}{
		"domain":       cfg.DNSTTDomain,
		"pubkey":       pubkey,
		"ssh_user":     user.Username,
		"ssh_port":     cfg.SSHPort,
		"dns_resolver": cfg.DNSResolver,
		"mtu":          cfg.MTU,
		"server_ip":    cfg.ServerIP,
	}

	jsonBytes, err := json.Marshal(linkData)
	if err != nil {
		return "", err
	}

	encoded := base64.URLEncoding.EncodeToString(jsonBytes)
	return fmt.Sprintf("dnstt://%s", encoded), nil
}

func GenerateConfigFile(user *models.User) (string, error) {
	cfg := config.Get()

	pubkey := ""
	if data, err := os.ReadFile(cfg.PubKeyFile); err == nil {
		pubkey = strings.TrimSpace(string(data))
	}

	content := fmt.Sprintf(`# DNSTT Configuration for %s
# Generated by DNSTT Manager
#
# This configuration connects through DNS tunnel to the server.

[tunnel]
domain = %s
pubkey = %s
mtu = %d
dns_resolver = %s

[ssh]
host = 127.0.0.1
port = %d
username = %s

[server]
ip = %s

# Client command example (Desktop):
# ./dnstt-client -doh %s -pubkey %s %s 127.0.0.1:7000
# Then: ssh -D 1080 -p %d %s@127.0.0.1
`,
		user.Username,
		cfg.DNSTTDomain,
		pubkey,
		cfg.MTU,
		cfg.DNSResolver,
		cfg.SSHPort,
		user.Username,
		cfg.ServerIP,
		cfg.DNSResolver,
		pubkey,
		cfg.DNSTTDomain,
		cfg.SSHPort,
		user.Username,
	)

	return content, nil
}
